---
# - include: install_conda.yml

- name: Make directory
  file: path={{ item }} state=directory owner=root
  with_items:
    - "{{ informix_home_dir }}{{ '/installer' }}"
    - "{{ informix_home_dir }}{{ '/infx' }}"
    - /opt/installer

- name: Install dependencies
  yum: name={{ item }} update_cache=yes
  with_items:
    - epel-release

- name: Install dependencies
  yum: name={{ item }} update_cache=yes
  with_items:
    - python-pip

- name: Install pexpect with pip
  pip: name=pexpect

- name: Manage Informix user
  user: name=informix shell=/bin/bash state=present

- name: Create pre-requisite files
  command: touch {{ item }} creates={{ item }}
  with_items:
    - "{{ informix_home_dir }}{{ '/rootdbs.' }}{{ informix_version }}" 
    - "{{ informix_home_dir }}{{ '/datadbs.' }}{{ informix_version }}" 
    - "{{ informix_home_dir }}{{ '/logbs.' }}{{ informix_version }}" 
    - "{{ informix_home_dir }}{{ '/phydbs.' }}{{ informix_version }}" 

- name: Uncompress Informix installer
  unarchive: src=files/Informix-11.70.FC4-x86_64.tar
             dest=/opt/installer 
             creates=/opt/installer/ids_install

- name: Run Installer
  command: ./ids_install -i silent -DLICENSE_ACCEPTED=TRUE -DUSER_INSTALL_DIR={{ informix_dir }}
  args: 
    chdir: /opt/installer
    creates: "{{ informix_dir }}"

- name: Install template bash_profile
  template: src=templates/.bash_profile dest=/root/.bash_profile

- name: Add saga services to /etc/services
  lineinfile: dest=/etc/services regexp='^{{ item.value.service_name }}\s'
              line="{{ item.value.service_name}}    {{ item.value.port }}    {{ '#' }} {{ item.value.service_name }}"
  with_dict: services
