---
# - include: install_conda.yml
- name: Create informix user
  user: name=informix

- name: Install dependencies
  package: name={{ item }} state=present
  with_items:
    - logrotate

- name: Add logrotate for informix log
  template: src=templates/db_logrotate dest=/etc/logrotate.d/informix

- name: Make directory
  file: path={{ item }} state=directory owner=informix
  with_items:
    - "{{ informix_dir }}"
    - "{{ informix_home_dir }}{{ '/installer' }}"
    - "{{ informix_home_dir }}{{ '/infx' }}"
    - /opt/installer

- name: Copy over bashrc and bash_profile
  template: src=templates/{{ item }} dest=/home/informix/{{ item }}
  with_items:
    - .bashrc
    - .bash_profile
 
- name: Create pre-requisite files
  command: touch {{ item }} creates={{ item }}
  with_items:
    - "{{ informix_home_dir }}{{ '/rootdbs.' }}{{ informix_version }}" 
    - "{{ informix_home_dir }}{{ '/datadbs.' }}{{ informix_version }}" 
    - "{{ informix_home_dir }}{{ '/logbs.' }}{{ informix_version }}" 
    - "{{ informix_home_dir }}{{ '/phydbs.' }}{{ informix_version }}" 
  become: true
  become_user: informix

- name: Chmod 660 rootdbs file
  file: 
    path: "{{ informix_home_dir }}{{ '/rootdbs.' }}{{ informix_version }}"
    owner: informix
    group: informix
    mode: 0660

- name: Uncompress Informix installer
  unarchive: src=files/Informix-11.70.FC4-x86_64.tar
             dest=/opt/installer 
             creates=/opt/installer/ids_install

- name: Run Installer
  command: ./ids_install -i silent -DLICENSE_ACCEPTED=TRUE -DUSER_INSTALL_DIR={{ informix_dir }}
  args: 
    chdir: /opt/installer
    creates: "{{ informix_dir }}{{ '/uninstall' }}"

- name: Install onconfig.csmsaga
  template: src=templates/onconfig.csmsaga dest={{ informix_dir }}/etc/onconfig.csmsaga

- name: Initialize
  shell: ". ~/.bash_profile {{ informix_dir }}{{ '/bin/oninit -ivy' }}" 
  become: true
  become_user: informix

- name: Finalize initializations
  command: /bin/bash  ~/.bash_profile onspaces -c -d datadbs -p {{ informix_home_dir }}/{{ item.filename }}.11.001 -o 0 -s {{ item.setting_value }}
  become: true
  become_user: informix
  with_items:
     - { filename: "datadbs", setting_value: 20000000 }
     - { filename: "logdbs", setting_value: 50000000 }
     - { filename: "phydbs", setting_value: 50000000 }
     - { filename: "tmpdbs", setting_value: 50000000 }

- name: Add saga services to /etc/services
  lineinfile: dest=/etc/services regexp='^{{ item.value.service_name }}\s'
              line="{{ item.value.service_name}}    {{ item.value.port }}    {{ '#' }} {{ item.value.service_name }}"
  with_dict: services
